"""#1270: /files honest source-provenance badge (content assertions).

A user must never mistake a Piper-generated document for one they uploaded
(CXO IA + PPM object-model). The /files surface already unifies two sources
(#355: uploaded files + generated artifacts as `kind`); this adds the *visible*
honest badge that was the load-bearing gap. Federated source is post-Beta
(RECONNECT/ADR-070). These guard the template wiring so a future edit can't
silently drop the provenance labeling.

Same content-assertion pattern as test_files_rename_1184 (the rename affordance
is also inline `renderFiles` JS). The badge palette is tentative pending CXO ratify.
"""

from pathlib import Path

import pytest


@pytest.fixture
def files_html() -> str:
    return (Path(__file__).resolve().parents[3] / "templates" / "files.html").read_text()


def test_source_badge_is_keyed_on_kind(files_html):
    assert "const sourceBadge =" in files_html, "sourceBadge not built in renderFiles"
    # artifact → generated; everything else → uploaded (kind is the #355 discriminator)
    assert "kind === 'artifact'" in files_html
    assert 'class="source-badge generated"' in files_html
    assert 'class="source-badge uploaded"' in files_html


def test_generated_badge_is_honest_about_piper_origin(files_html):
    # The disambiguating label PPM required: clearly Piper-authored, not user-uploaded.
    assert "Generated by Piper" in files_html
    assert "Uploaded" in files_html


def test_source_badge_is_rendered_into_each_row(files_html):
    # It must actually appear in the .file-card metadata, not just be defined.
    metadata_seg = files_html.split('<div class="file-metadata">')[1].split("</div>")[0]
    assert "${sourceBadge}" in metadata_seg, "sourceBadge defined but not rendered into the row"


def test_source_badge_styles_exist(files_html):
    assert ".source-badge {" in files_html
    assert ".source-badge.generated {" in files_html
    assert ".source-badge.uploaded {" in files_html
